version: '3'

services:
  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   restart: always
  #   networks:
  #     - monitoring

  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - grafana-storage:/var/lib/grafana
  #   restart: always
  #   networks:
  #     - monitoring
  #   depends_on:
  #     - prometheus

  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    restart: always
    networks:
      - monitoring

  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=auto #aws.gameue.mx
      - SERVERPORT=51820
      - PEERS=2
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      - monitoring

  # Servidor de correo (Poste.io)
  mailserver:
    image: analogic/poste.io
    restart: always
    container_name: poste
    hostname: mail
    domainname: gameue.mx
    network_mode: "host"
    expose:
      - 25
      - 80
      - 443
      - 110
      - 143
      - 465
      - 587
      - 993
      - 995
      - 4190
    # ports:
    #   - "25:25"
    #   - "8080:8080"
    #   - "110:110"
    #   - "143:143"
    #   - "465:465"
    #   - "587:587"
    #   - "993:993"
    #   - "995:995"
    #   - "4190:4190"
    environment:
      - HTTPS=ON
      - DISABLE_CLAMAV=TRUE
      - TZ=America/Chicago
      # - HTTP_PORT=8080
    volumes:
      - maildata:/data

volumes:
  grafana-storage:
  portainer-data:
  maildata:

networks:
  monitoring: